spring:
  application:
    name: eureka-consumer-feign-hystrix
server:
  port: 8075
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8050/eureka/

feign:
  hystrix:
    enabled: true
